engines:
  eslint:
    enabled: true
ratings:
   paths:
   - src/**
   - "**.js"
exclude_paths:
- ./node_modules/**/*
- boldrCMS/**
- db/**
- docs/**
- bin/**
- flow-typed/**
- tools/**
- src/**/*.test.js
